API_HOST_URL: 'http://prometheus.org.ua'
ENVIRONMENT_DISPLAY_NAME: 'Prometheus'
PLATFORM_NAME: 'Prometheus'
FEEDBACK_EMAIL_ADDRESS: 'support@prometheus.org.ua'
USER_PROFILES_ENABLED: TRUE
DISCUSSIONS_ENABLED: TRUE
CERTIFICATIONS_ENABLED: TRUE
NEW_LOGISTRATION_ENABLED: FALSE
PUSH_NOTIFICATIONS: FALSE

COURSE_ENROLLMENT: {
 TYPE: 'native'
}
FABRIC: {
    ENABLED: true,
    FABRIC_KEY: "013155ba3de2508e862ee784e2d646bcb76eb7d5",
    BUILD_SECRET: "840b47e08fcd996e1449f0fa7797c084595b82d31241cd90e35ba651ba61344b"
}