API_HOST_URL: 'http://prometheus-test-server.cloudapp.net'
ENVIRONMENT_DISPLAY_NAME: 'Prometheus'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
USER_PROFILES_ENABLED: TRUE
DISCUSSIONS_ENABLED: TRUE
CERTIFICATIONS_ENABLED: TRUE
NEW_LOGISTRATION_ENABLED: TRUE

COURSE_ENROLLMENT:
 TYPE: 'native'
 WEBVIEW:
  COURSE_SEARCH_URL: 'http://courses.prometheus.org.ua/courses'
  COURSE_INFO_URL_TEMPLATE: 'http://courses.prometheus.org.ua/courses/{path_id}/about'
  SEARCH_BAR_ENABLED: TRUE	
