API_HOST_URL: 'https://courses.prometheus.org.ua/'
ENVIRONMENT_DISPLAY_NAME: 'Prometheus'
PLATFORM_NAME: 'Prometheus'
PLATFORM_DESTINATION_NAME: 'prometheus.org.ua'
FEEDBACK_EMAIL_ADDRESS: 'support@prometheus.org.ua'
USER_PROFILES_ENABLED: TRUE
DISCUSSIONS_ENABLED: TRUE
CERTIFICATIONS_ENABLED: TRUE
NEW_LOGISTRATION_ENABLED: TRUE
ENABLE_MOBILE_REST_API: true
ENABLE_COMBINED_LOGIN_REGISTRATION: true

COURSE_ENROLLMENT: {
 ENABLED: TRUE,
 TYPE: 'native',
 EXTERNAL_COURSE_SEARCH_URL: 'https://courses.prometheus.org.ua/'
}

FABRIC: {
    ENABLED: TRUE,
    FABRIC_KEY: "013155ba3de2508e862ee784e2d646bcb76eb7d5",
    BUILD_SECRET: "840b47e08fcd996e1449f0fa7797c084595b82d31241cd90e35ba651ba61344b"
}